language: python
python: 
  - "3.6"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run before to run tests
before_script: "flake8 --max-complexity=5 --ignore=E501 django-polls"
# command to run tests
script: python mysite/manage.py test polls